### PR TITLE
Add Wedbio.com

### PR DESCRIPTION
**Pull request by darrylsepeda**

### CODE REVIEW

**Comment by yesnet0** [comment]
Thanks Darryl! I recommend you take a look at the Safe Harbor terms in https://github.com/disclose/disclose/tree/master/terms and consider adding either Partial or Full safeharbor terms to your policy.

**Comment by darrylsepeda** [comment]
Yes, we are currently working on it..
thanks for reminding.

**Comment by darrylsepeda** [comment]
Hi @yesnet0, we have modified the url for safe harbor terms.
please kindly review again. thank you

**Comment by codingo** [comment]
Given the above commentary I've updated this to reflect a full safe harbor. Once reviewed by another author I will merge.

**Comment by darrylsepeda** [comment]
thanks @codingo, I'll wait for other reviewers to approve

**Comment by darrylsepeda** [comment]
Can anyone help on this PR? should I rebase this PR or is there any automatic way to rebase this?

**Comment by prodigysml** [comment]
Hey @darrylsepeda! Apologies, but I think I stuffed something up in the PR. Would be appreciated if you could do another PR by doing a `git clone` of the repo, making your changes again, and then putting in another PR. I can get that resolved for you quickly.

**Pull request closed without merging**
