### PR TITLE
Added some Programs

### PR DESCRIPTION
**Pull request by abhinavprasad47**
i added notion.so to the list of programs

### CODE REVIEW

**Comment by codingo** [comment]
There's a lot here to review so I won't get through all of it today. Regardless, if you can comment here with your Twitter username so I can dm you a free month of Pentesterlab as a thank-you for your efforts.

**Comment by abhinavprasad47** [comment]
https://twitter.com/abhinavprasad47

**Comment by abhinavprasad47** [comment]
Thanks you sir 
And I will also try to make some build script as mention in one of the issues for comparison

**Comment by codingo** [comment]
Great! Pentesterlab subscription sent as promised.

**Comment by abhinavprasad47** [comment]
sir could you merege it as if it as fast as possibe or there will more merge conflits and i just resolved some

**Comment by codingo** [comment]
Hi @abhinavprasad47, we're planning to review and merge this after #153 is completed and in place. Thank-you for resolving the conflicts!

**Pull request merged**
