### PR TITLE
Update program-list.json

### PR DESCRIPTION
**Pull request by troubledecker**
Added 7 new programs to program-list.json: Athento, LoginRadius, Spreaker, StarLeaf, Synology, TechGig, and Vultr. Six of them have a declared bug bounty program, while TechGig only has a Hall of Fame. 

I have a few doubts about LoginRadius's safe harbor field, and have chosen Partial to reflect these doubts.

### CODE REVIEW

**Comment by troubledecker** [comment]
Deleted AncientBrain since its bug bounty program is on pause.

**Comment by hakluke** [comment]
Hey troubledecker!

Thank-you! If you comment on this issue with your twitter handle I'll send you a free month of pentesterlab (as per https://twitter.com/codingo_/status/1246266810065813510)

**Comment by troubledecker** [comment]
Thank you. @troubledecker

**Comment by codingo** [comment]
Thank-you! This has now been sent.

**Pull request merged**
