### PR TITLE
Update to program-list.csv and program-list.json,added new programs

### PR DESCRIPTION
**Pull request by ankitr82991**

### CODE REVIEW

**Comment by ankitr82991** [comment]
Checking for updates on every 5 min if i'll eligible to get a sub. I'm so excted.

**Comment by ankitr82991** [comment]
Hello sir,any updates?

**Comment by codingo** [comment]
Thank-you! Could you please list your twitter here so I can send you a one month pentesterlab voucher for your contribution.

**Comment by ankitr82991** [comment]
https://twitter.com/A2991R

**Comment by ankitr82991** [comment]
resolved the conflict

**Comment by codingo** [comment]
Hi @ankitr82991 as your dm's are closed could you please follow me so I can send this to you? I'm https://twitter.com/codingo_

**Comment by ankitr82991** [comment]
Done sir.

**Comment by codingo** [comment]
Thank-you, this has been sent!

**Pull request closed without merging**
