### PR TITLE
added new bug bounty program

### PR DESCRIPTION
**Pull request by tectjay**

### CODE REVIEW

**Comment by hakluke** [comment]
Hi Jay-dalal,

Thank-you! If you can comment your twitter profile on this issue I'll send you a free month of pentesterlab (as per https://twitter.com/codingo_/status/1246266810065813510)

**Comment by tectjay** [comment]
Hi, 
thanks, [https://twitter.com/tectjay](https://twitter.com/tectjay) is my twitter profile

**Comment by tectjay** [comment]
Hi, @codingo  any update ?

**Comment by tectjay** [comment]
Hi, @hakluke @codingo  any update?

**Pull request merged**
