### PR TITLE
Added Some Programs and modified the list

### PR DESCRIPTION
**Pull request by ZyperX**
Added the following programs in csv and json file:-

Issuu
Scraping Hub

Happy to contibure :-)

### CODE REVIEW

**Comment by codingo** [comment]
Thank-you! Could you please list your twitter here so I can send you a one month pentesterlab voucher for your contribution.

**Comment by ZyperX** [comment]
@x_zyper this is my twitter.
thx  :-)

**Comment by ZyperX** [comment]
> Thank-you! Could you please list your twitter here so I can send you a one month pentesterlab voucher for your contribution.

@x_zyper this is my twitter account

**Comment by codingo** [comment]
Hy @ZyperX as your dm's are closed could you please follow me so I can send this to you? I'm https://twitter.com/codingo_

**Comment by ZyperX** [comment]
i have followed you @codingo

**Comment by codingo** [comment]
Thank-you! Sent for you now.

**Pull request merged**
