### PR TITLE
Added PayTm and Swiggy bug bounty in program list

### PR DESCRIPTION
**Pull request by rajanimesh64**

### CODE REVIEW

**Comment by rajanimesh64** [comment]
Hello sir, What else should i do to contribute?

**Comment by codingo** [comment]
Excellent, thank-you. If you can comment here with your twitter account and I'll dm you a one month pentesterlab subscription in thanks for your contribution.

**Comment by rajanimesh64** [comment]
https://twitter.com/animesh4real

**Comment by rajanimesh64** [comment]
image

**Comment by rajanimesh64** [comment]
Hello sir, any updates?

**Comment by rajanimesh64** [comment]
sir, any new update for this thread?

**Comment by codingo** [comment]
Ah! Sorry about that, I saw I'd given you a pentesterlab but didn't realise it was from a previous giveaway of mine. I've sent you a new one now, enjoy!

**Pull request merged**
