### PR TITLE
Update program-list.json

### PR DESCRIPTION
**Pull request by oyekss**
Updated the program-list.json list with qwant and pfizer

### CODE REVIEW

**Comment by codingo** [comment]
Thank-you! Could you please list your twitter here so I can send you a one month pentesterlab voucher for your contribution.

**Comment by oyekss** [comment]
> Thank-you! Could you please list your twitter here so I can send you a one month pentesterlab voucher for your contribution.

@oyekss  Thank you!

**Comment by codingo** [comment]
Thank-you! This has now been sent

**Comment by codingo** [comment]
Thank-you, sorry for the delay here - this was a pretty tricky conflict to work through. Confirmed valid/working json and re-validated these entries.

**Pull request merged**
