### PR TITLE
Add Shape Security VDP Listing

### PR DESCRIPTION
**Pull request by sahsarva**
# Summary
< a quick summary of the associated pull request >

# Quality Assurance Checklist
< confirmation of this pull request meeting the following requirements, prior to merge >
| Review Items                            | Y/N |
|-----------------------------------------|-----|
| Site has a publicly known bug bounty    |  Y   |
| Disclosure terms are publicly available |  Y |
| Public URL                              |   Y  |
| Single Source, or all sources appended  |  Y   |

### CODE REVIEW

**Comment by sahsarva** [comment]
Thank you @codingo ! When will this change be reflected in the public list? https://www.bugcrowd.com/bug-bounty-list/

**Comment by sahsarva** [comment]
Hey @codingo our program is still not visible on https://www.bugcrowd.com/bug-bounty-list/.  Does it need any more details from my side?

**Comment by yesnet0** [comment]
Hi @sahsarva - The Bugcrowd List and the disclose.io repo operate separately. You can expect to see it soon on the Bugcrowd site soon.

**Comment by sahsarva** [comment]
Hey @yesnet0 Still cant see it on the program list :/ Can we get reach out to someone in Bugcrowd to get this fixed? Thanks!

**Pull request merged**
