### PR TITLE
Add Wedbio.com

### PR DESCRIPTION
**Pull request by darrylsepeda**
# Summary
Please help to merge this PR immediately.
This is my second PR, because previous PR was not merged into master.
Thank you

### CODE REVIEW

**Comment by darrylsepeda** [comment]
Hey @prodigysml, this is my 2nd pull request after you asked me to create new PR #181.
Please help to merge this PR.
Thank you.

**Comment by prodigysml** [comment]
Apologies for the delay here @darrylsepeda. Fixed up the conflict. Good to merge into master now.

**Comment by darrylsepeda** [comment]
Thank you @prodigysml, I really appreciate your help!

**Comment by prodigysml** [comment]
Any time mate! Thanks for being patient and working with us to get this PR in!

**Pull request merged**
