### PR TITLE
Update program-list.json

### PR DESCRIPTION
**Pull request by ajaysenr**

### CODE REVIEW

**Comment by codingo** [comment]
@ajaysenr can you resolve the conflicts here so we can look at a merge?

**Comment by ajaysenr** [comment]
program-list.json
   
     "program_name": "certifix"
        "program_name": "Certifix"
        "policy_url": "https://app.certifix.eu/security.txt"
        "submission_url": "security@certifix.eu"
        "launch_date": "",

**Comment by codingo** [comment]
@ajaysenr just touching base to see how you're going resolving conflicts here, or if you'd like me to handle it for you?

**Comment by ajaysenr** [comment]
Can you handle it.

**Pull request merged**
