### PR TITLE
Update program-list

### PR DESCRIPTION
**Pull request by aybulgin**
Hello, added a new program on the bug bounty json list.
Saw you on codingo twitter :)

### CODE REVIEW

**Comment by hakluke** [comment]
Hey @aybulgin, thanks for the PR!
Can you also add this to the CSV program list?

**Comment by aybulgin** [comment]
Updated csv

**Comment by codingo** [comment]
Excellent, thank-you! If you can comment with your twitter handle here I'll send you a one month pentesterlab subscription in thanks for your efforts!

**Comment by aybulgin** [comment]
Thank you for approving! This is an amazing repository.
My twitter handle is @0xblackbunny

**Comment by aybulgin** [comment]
Thank you for approving @codingo ! This is an amazing repository.
My twitter is https://twitter.com/0xblackbunny

**Comment by codingo** [comment]
Thank-you!  This has now been sent.

**Pull request merged**
