### PR TITLE
Update program-list.json

### PR DESCRIPTION
**Pull request by sgdavidw**
Update bug_bounty and hall_of_fame status.

# Summary
< a quick summary of the associated pull request >

# Quality Assurance Checklist
< confirmation of this pull request meeting the following requirements, prior to merge >
| Review Items                            | Y/N |
|-----------------------------------------|-----|
| Site has a publicly known bug bounty    |     |
| Disclosure terms are publicly available |     |
| Public URL                              |     |
| Single Source, or all sources appended  |     |

### CODE REVIEW

**Comment by sgdavidw** [comment]
I have tried filling or un-filling the Quality Assurance Checklist form, but both got validate-links failed.
Would you please approve this pull request?
Thanks,

**Comment by Parasdogra** [comment]
I tried different url too but both got validate-links failed.
can you please approve this PR.
Thanks

**Comment by codingo** [comment]
Thank-you!

**Comment by sgdavidw** [comment]
Hi, Michael,
Thank you for approving my pull request. I saw that program-list.json has been updated:
https://github.com/disclose/disclose/blob/master/program-list/program-list.json
But the bug bounty status of F5 Networks is unchanged on https://www.bugcrowd.com/bug-bounty-list/.
When the update will be pushed to https://www.bugcrowd.com/bug-bounty-list/?
Thank you,
David


> Thank-you!

**Pull request merged**
