### PR TITLE
Change bug_bounty to true for Savedroid and Add MTN Group to program-list

### PR DESCRIPTION
**Pull request by deepak-pro**
Savedroid does reward vulnerabilities.

### CODE REVIEW

**Comment by codingo** [comment]
Hi deepak-pro,

Thank-you! If you can list your twitter profile here I'll send you a free month of pentesterlab (as per https://twitter.com/codingo_/status/1246266810065813510)

**Comment by deepak-pro** [comment]
Thank you very much, here is my twitter profile details:-
Username: 0xjoshi
Profile link: https://twitter.com/0xjoshi

**Comment by deepak-pro** [comment]
When should I expect the giveaway?

**Comment by codingo** [comment]
Hi @deepak-pro my apologies, sending this to you now

**Comment by deepak-pro** [comment]
Thank you very much.

**Pull request merged**
