### PR TITLE
Refactor tools code

### PR DESCRIPTION
**Pull request by mendesfabio**
This pull request fixes the Conversor JSON to CSV file name and improves some lines of python code.

### CODE REVIEW

**Comment by seantitmarsh** [comment]
Appreciate the fixes, espcially the args code, I'll take a note of that for the future. 

With respect to itemgetter, if we use that rather than the lambda function, the end of the output looks like this:

~~~~
--snip--
{
    "program_name": "Zscaler",
    "policy_url": "https://www.zscaler.com/company/vulnerability-disclosure-program",
    "submission_url": "https://www.zscaler.com/vulnerability-disclosure-form",
    "launch_date": "",
    "bug_bounty": false,
    "swag": false,
    "hall_of_fame": false,
    "safe_harbor": ""
  },
  {
    "program_name": "Zynga Whitehat",
    "policy_url": "https://bugcrowd.com/zynga-vdp",
    "submission_url": "https://bugcrowd.com/zynga-vdp/report",
    "launch_date": "",
    "bug_bounty": false,
    "swag": false,
    "hall_of_fame": true,
    "safe_harbor": "partial"
  },
  {
    "program_name": "cPanel",
    "policy_url": "https://cpanel.net/cpanel-security-bounty-program/",
    "submission_url": "security@cpanel.net",
    "launch_date": "",
    "bug_bounty": true,
    "swag": false,
    "hall_of_fame": true,
    "safe_harbor": ""
  },
  {
    "program_name": "cPaperless",
    "policy_url": "https://www.cpaperless.com/security-statement/",
    "submission_url": "support@cPaperless.com",
    "launch_date": "",
    "bug_bounty": false,
    "swag": false,
    "hall_of_fame": false,
    "safe_harbor": ""
  },
--snip--
~~~~

~~~~
--snip--
Zscaler,https://www.zscaler.com/company/vulnerability-disclosure-program
Zynga Whitehat,https://bugcrowd.com/zynga-vdp
cPanel,https://cpanel.net/cpanel-security-bounty-program/
cPaperless,https://www.cpaperless.com/security-statement/
--snip--
~~~~
This is because the sort function treats capitals - all capitals - as coming before lower case letters in the alphabet. It's only a few companies that start with a lower case letter, but I can see people re-adding them, assuming that because they don't appear under "C", they aren't in the list at all.

**Comment by codingo** [comment]
Holding on this until the above is addressed

**Comment by mendesfabio** [comment]
@seantitmarsh Thanks! I didn't pay attention that sorting using itemgetter is case-sensitive.

**Comment by mendesfabio** [comment]
@codingo You can merge it. Hope I helped you!

**Comment by seantitmarsh** [comment]
@mendesfabio Looks good now. I've closed my PR in favour of this one.

I didn't actually know about the case sensitivity of sort with itemgetter until yesterday, it took an hour or so of tearing my hair out to find out about the way python sorts alphabetically. Good learning experience though.

@codingo, agreed, this one is good to merge now.

**Comment by codingo** [comment]
Thank-you! Could you please list your twitter here so I can send you a one month pentesterlab voucher for your contribution.

**Comment by mendesfabio** [comment]
Thanks! Here it is: https://twitter.com/fabiomendesafc

**Comment by codingo** [comment]
Thank-you! This has now been sent.

**Pull request merged**
